name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: __tea_cookie_tokens_2608=%257B%2522user_unique_id%2522%253A%25227248909894823478824%2522%252C%2522web_id%2522%253A%25227248909894823478824%2522%252C%2522timestamp%2522%253A1702018147373%257D; passport_csrf_token=4c922ebe3ae155bf5c55da1edfe1d723; passport_csrf_token_default=4c922ebe3ae155bf5c55da1edfe1d723; n_mh=XC9UYpK2kjnTAX61kRV0k15y9dFQlBwpHCfek8Q-Wew; passport_auth_status=19ab461b5953942fa695228b65bca893%2C; passport_auth_status_ss=19ab461b5953942fa695228b65bca893%2C; sid_guard=3e711eddd763402fa0c080fddf6f1eaa%7C1702257628%7C31536000%7CTue%2C+10-Dec-2024+01%3A20%3A28+GMT; uid_tt=eadd5ced8922e19a46d43d6ee07e9f6e; uid_tt_ss=eadd5ced8922e19a46d43d6ee07e9f6e; sid_tt=3e711eddd763402fa0c080fddf6f1eaa; sessionid=3e711eddd763402fa0c080fddf6f1eaa; sessionid_ss=3e711eddd763402fa0c080fddf6f1eaa; sid_ucp_v1=1.0.0-KDkxYjQwY2M1NWMyODBkMzM0M2IyZjA4MTRjYmYxNDNkN2IwNmQ3ODYKFwjuveHA_fWFBhDcx9mrBhiwFDgCQPEHGgJsZiIgM2U3MTFlZGRkNzYzNDAyZmEwYzA4MGZkZGY2ZjFlYWE; ssid_ucp_v1=1.0.0-KDkxYjQwY2M1NWMyODBkMzM0M2IyZjA4MTRjYmYxNDNkN2IwNmQ3ODYKFwjuveHA_fWFBhDcx9mrBhiwFDgCQPEHGgJsZiIgM2U3MTFlZGRkNzYzNDAyZmEwYzA4MGZkZGY2ZjFlYWE; store-region=cn-js; store-region-src=uid; msToken=yFZIICEOL_zhL2gzReRg_LeElZwbUfvV1Lk-ziS_NQ5qAPSrA5e62ZcDfkeiHkj0R-6AaJOPxz99g7lqEwvYfGY8516GgYhEl8_2Vj-MDA_8DDAKt71enTWEqsskw7gH8Q==
  COOKIE_2: _tea_utm_cache_2608=undefined; __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227277825527917168163%2522%252C%2522user_unique_id%2522%253A%25227277825527917168163%2522%252C%2522timestamp%2522%253A1694500814196%257D; n_mh=aCBw4Dbk6mM55RjpNsv4SDZh1i-zV-llZ1wjv7JS1lk; sid_guard=0fafa7ec05e035c20c6bd979f721565f%7C1694500835%7C31536000%7CWed%2C+11-Sep-2024+06%3A40%3A35+GMT; uid_tt=a5a84d4d9df0bb7c02a9d571e4ab9118; uid_tt_ss=a5a84d4d9df0bb7c02a9d571e4ab9118; sid_tt=0fafa7ec05e035c20c6bd979f721565f; sessionid=0fafa7ec05e035c20c6bd979f721565f; sessionid_ss=0fafa7ec05e035c20c6bd979f721565f; sid_ucp_v1=1.0.0-KDBkNzAwMmNkZjljZDQyNDc5YjFjYzM3MTcwNDQzMmQ5Y2Q1ZjE2NGYKFwju-aDW0ozSAxDjj4CoBhiwFDgHQPQHGgJscSIgMGZhZmE3ZWMwNWUwMzVjMjBjNmJkOTc5ZjcyMTU2NWY; ssid_ucp_v1=1.0.0-KDBkNzAwMmNkZjljZDQyNDc5YjFjYzM3MTcwNDQzMmQ5Y2Q1ZjE2NGYKFwju-aDW0ozSAxDjj4CoBhiwFDgHQPQHGgJscSIgMGZhZmE3ZWMwNWUwMzVjMjBjNmJkOTc5ZjcyMTU2NWY; store-region=cn-js; store-region-src=uid; csrf_session_id=f886f756ac1a3af7954970874c4c89aa; msToken=gPPj_d0Js_rxj5ys5i5UsYN9oGFhw_v1nCN8Fnr6e4I835s_q80Tl2i-y7lU2BWXfh0-BvnZ_gVJvrrE8ij6AU7HDsnE05Lq9rguWNiW9lK0-HodQCbPubICOWwci5g=
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
